### ISSUE TITLE
 add .cow logo files

### ISSUE THREAD

**Issue by mememan77** [SpamixOfficial/fetch#3]
place the logos on individual files instead of the source code

**Comment by mememan77** [comment]
in addition to this it would be nice if you could for example have something like .cow files in cowsay to add logos  easily

**Comment by mememan77** [comment]
> place the logos on individual files instead of the source code

discard this i didnt read the plans file

**Comment by SpamixOfficial** [comment]
> in addition to this it would be nice if you could for example have .cow files like in cowsay to add logos  easily

I'll add this to the plans!

**Comment by SpamixOfficial** [comment]
Okay so implementing the cow format might not be a bad idea if it supports colors. If it doesnt, we will implement out own cow-based format I guess!

**Comment by SpamixOfficial** [comment]
Okay I just realized cowfiles are just perl code....cool! Sadly this is not a perl project so cowfiles might be kind of an...issue



EDIT: I will put this issue on ice for now, and revisit it if I find it worth it. Cheers!
